micronaut:
  application:
    name: keyManager
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5433/key-manager-db`}
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
#jpa.default.properties.hibernate.hbm2ddl.auto: create-drop

logger:
  levels:
    io.micronaut.transaction: DEBUG

application.client:
  itau: http://localhost:9091
  bcb: http://localhost:8082